# Generated by Django 4.2 on 2024-02-11 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_download_speed', models.FloatField()),
                ('max_download_speed', models.FloatField()),
                ('avg_download_speed', models.FloatField()),
                ('min_upload_speed', models.FloatField()),
                ('max_upload_speed', models.FloatField()),
                ('avg_upload_speed', models.FloatField()),
                ('ping', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
